spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
